#!/bin/bash
##
## EPITECH PROJECT, 2021
## Epitech - keyring_solver.sh
## File description:
## abc
##

OA='\033[1;32m\033[1;40m'
OE='\033[1;33m\033[1;40m'
filename="login.keyring"
rendfilename="${filename}(safe_backup)"
destFoldName="keyring_backup"
theSource="${HOME}/.local/share/keyrings/${filename}"
theDest="${HOME}/${destFoldName}/${rendfilename}"
decoLine="###########################################################"
treat(){
    echo -ne "Making sure that we are located in ${HOME}\n"
    cd ${HOME}
    echo -ne "Creating folder 'keyring_backup' in ${HOME}\n"
    mkdir ${destFoldName}
    echo -ne "Moving and renaming '${theSource}' to '${theDest}'\n"
    mv ${theSource} ${theDest}
    echo -ne "${OE}!!! Attention: !!!\n"
    echo -ne "${OA}You will now log out and then log back into your computer\n"
    echo -ne "This is to recreate the login keyring file\n\n"
    sleep 2s
    echo -ne "${OE}!!!! Attention: !!!!\n"
    echo -ne "${OA}Once you are logged back in, run one of the programs that generaly asks for the login keyring:\n"
    echo -ne "- If it does not require it anymore, this means that you have succesefully repared your loggin keyring.\n"
    echo -ne "- If this is not the case:\n"
    echo -ne "      * You can try running the program again\n"
    echo -ne "   or * Do your own research\n"
}
echo -ne "${OA}\n"
echo off
clear
#              ####################     ######################################     #
echo -ne "${OE}${decoLine}\n"
echo -ne "${OE}#                      ${OA}WELCOME TO                         ${OE}#\n"
echo -ne "${OE}#                 ${OA}THE KEYRING SOLVER                      ${OE}#\n"
echo -ne "${OE}#                   ${OA}                                      ${OE}#\n"
echo -ne "${OE}#                      ${OA}Created by                         ${OE}#\n"
echo -ne "${OE}#                   ${OA}                                      ${OE}#\n"
echo -ne "${OE}#                ${OA}(c) Henry Letellier                      ${OE}#\n"
echo -ne "${OE}#                   ${OA}                                      ${OE}#\n"
echo -ne "${OE}#                   ${OA}    Website:                          ${OE}#\n"
echo -ne "${OE}#         ${OA}https://hanralatalliar.wordpress.com/           ${OE}#\n"
echo -ne "${OE}${decoLine}${OA}\n\n"
echo "Do you wish to repaire your keyring problems?"
PS3='> '   # le prompt
LISTE=("[y] yes" "[n] no") # liste de choix disponibles
select CHOIX in "${LISTE[@]}" ; do
    case $REPLY in
        0|y)
            treat
            break
            ;;
        1|n)
            echo -ne "You have decided to not touch your keyring\n"
            echo -ne "It will thus remain as is, untouched by this program.\n"
            break
            ;;
    esac;
done
echo -ne "\nEnd of Script.\n"
